version: '3.8'

services:
  db:
    container_name: autospace_db
    image: postgres
    restart: always
    ports:
      - 2010:5432
    environment:
      POSTGRES_USER: autoSpace
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: autoSpace
    volumes:
      - db_data_autospace:/var/lib/postgresql/data
    
volumes:
  db_data_autospace: